name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # or your version

      - name: Add NuGet source
        run: |
          dotnet nuget add source ${{ secrets.NUGET_URL }} \
            --name MyPrivateFeed \
            --username ${{ secrets.NUGET_USERNAME }} \
            --password ${{ secrets.NUGET_PASSWORD }} \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          upload-result: true
